django_htmx_my_tailwind/core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.views'))

]

my_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first_app.urls'))
]

myfirst/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # in blogs all the html template for creating this app
    path('blogs/', views.blogs),
    path('', views.index),


    path('posts/', views.index, name="post_index"),
    path('posts/<int:post_id>', views.show, name="post_show"),
    path('posts/create', views.create, name='post_create'),
    path('posts/store', views.store, name="post_store"),
    path('posts/update/<int:post_id>', views.update, name="post_update"),
    path('posts/delete/<int:post_id>', views.delete, name="post_delete"),



    path('mod/', views.modss),
    # path('', views.home)

]

urls.py
# from django.contrib import admin
from django.urls import path

from rest_framework.decorators import api_view
from rest_framework.response import Response

from django.db import models
from rest_framework.serializers import ModelSerializer


class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.CharField(max_length=500)


class PostSerializer(ModelSerializer):
    class Meta:
        model = Post
        fields = '__all__'


''' ---------------------------------------
all necessary fucntions for view is below'''


@api_view(['GET'])
def index(request):
    posts = Post.objects.all()
    serialPosts = PostSerializer(posts, many=True)

    return Response(serialPosts.data)


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('home/', index)


]

myfirst/models.py
from django.db import models


class Posts(models.Model):
    title = models.CharField(max_length=5)
    body = models.CharField(max_length=500)

myfirst/forms.py
from django import forms
from django.forms import fields
from .models import Posts


class InputForm(forms.Form):
    title = forms.CharField(max_length=5)
    body = forms.CharField(max_length=500,widget=forms.Textarea)


class InputFormModel(forms.ModelForm):
    class Meta:
        model = Posts
        fields = "__all__"

myfirst/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from myfirst import models
from myfirst import forms


def blogs(request):
    return render(request, 'blogs.html')


def index(request):
    all_posts = models.Posts.objects.all()
    return render(request, 'index.html', {'posts': all_posts})


def show(request, post_id):
    # thepost = models.Posts.objects.get(id=post_id)
    thepost = get_object_or_404(models.Posts, id=post_id)
    return render(request, 'show.html', {'post': thepost})


def create(request):
    if request.method == 'POST':
        newform = forms.InputFormModel(request.POST or None)

        if newform.is_valid():
            newform.save()
        else:
            return render(request, 'create.html', {'form': newform})

    theform = forms.InputFormModel()

    return render(request, 'create.html', {'form': theform})


def store(request):
    ''' here is saving data without using form class'''
    # if request.method == 'POST':
    #     title = request.POST.get('title', '')
    #     body = request.POST.get('body', '')
    #     newpost = models.Posts(title=title, body=body)
    #     newpost.save()
    #     messages.success(request, "Post created successfull")
    #     return redirect('post_create')

    ''' here is saving data with normal Form Class the best way '''

    if request.method == 'POST':
        details = forms.InputForm(request.POST)

        if details.is_valid():
            title = details.cleaned_data.get('title', '')
            body = details.cleaned_data.get('body', '')
            newpost = models.Posts(title=title, body=body)
            newpost.save()
            messages.success(request, "Post created successfull")
            theform = forms.InputForm()
            return render(request, 'create.html', {'form': theform})
        else:
            return render(request, 'create.html', {'form': details})

    ''' here is saving data with modeForm '''
    # if request.method == 'POST':
    #     newform = forms.InputFormModel(request.POST or None)

    #     if newform.is_valid():
    #         newform.save()

    return render(request, 'create.html')


def update(request, post_id):

    theOj = models.Posts.objects.get(pk=post_id)

    if request.method == 'POST':
        ''' normal way of update but not recomendeed'''
        # theOj.title = request.POST.get('title', '')
        # theOj.body = request.POST.get('body', '')
        # theOj.save()

        newform = forms.InputFormModel(request.POST, instance=theOj)
        if newform.is_valid():
            newform.save()
            return redirect('post_index')
        else:
            return render(request, 'create.html', {'form': newform, 'pk_id': post_id})

    theform = forms.InputFormModel(instance=theOj)

    return render(request, 'update.html', {'form': theform, 'pk_id': post_id})


def delete(request, post_id):

    theOj = models.Posts.objects.get(pk=post_id)
    theOj.delete()

    # if request.method == 'POST':
    #     theOj.delete()

    return redirect('post_index')


def modss(request):

    # b1 = models.Posts()
    # b1.title = 'This is second three'
    # b1.body = 'This is the three body Some quick example text to build on the card title and make up the bulk of the card content. '
    # b1.save()

    all_entries = models.Posts.objects.all()

    for x in all_entries:

        print(x.title)

    return HttpResponse('success')

myfirst/templates/blogs.html
{% extends 'layouts/base_layout.html' %} 
{% load static %}
{% block content %}


<section class="fdb-block" data-block-type="contents" data-id="2" draggable="true">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-12 col-md-6 mb-4 mb-md-0">
          <img alt="image" class="img-fluid"
            src="https://cdn.jsdelivr.net/gh/froala/design-blocks@master/dist/imgs//draws/smile.svg">
        </div>
        <div class="col-12 col-md-6 col-lg-5 ml-md-auto text-left">
          <h1>Froala Blocks</h1>
          <p class="lead">A small river named Duden flows by their place and supplies it with the necessary regelialia.
            It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
          <p><a class="btn btn-purple mt-4" href="https://www.froala.com">Download</a></p>
        </div>
      </div>
    </div>
  </section>



<section class="fdb-block">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-12 col-md-8 col-lg-8 col-xl-6">
            <div class="row">
              <div class="col text-center">
                <h1>Register</h1>
                <p class="lead">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia. </p>
              </div>
            </div>
            <div class="row align-items-center">
              <div class="col mt-4">
                <input type="text" class="form-control" placeholder="Company Name">
              </div>
            </div>
            <div class="row align-items-center mt-4">
              <div class="col">
                <input type="email" class="form-control" placeholder="Email">
              </div>
            </div>
            <div class="row align-items-center mt-4">
              <div class="col">
                <input type="password" class="form-control" placeholder="Password">
              </div>
              <div class="col">
                <input type="password" class="form-control" placeholder="Confirm Password">
              </div>
            </div>
            <div class="row justify-content-start mt-4">
              <div class="col">
                <div class="form-check">
                  
                      <input type="checkbox" class="form-check-input" id= "formcheck1">
                      <label class="form-check-label" for="formcheck1">
                      I Read and Accept <a href="https://www.froala.com">Terms and Conditions</a>
                    </label>
                </div>
    
                <button class="btn btn-purple mt-4">Submit</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>



  <section class="fdb-block fp-active" data-block-type="forms" data-id="4" draggable="true">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-12 col-md-8 col-lg-8 col-xl-6">
          <div class="row">
            <div class="col text-center">
              <h1>Register</h1>
              <p class="lead">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia.
              </p>
            </div>
          </div>
          <div class="row align-items-center">
            <div class="col mt-4">
              <input type="text" class="form-control" placeholder="Company Name">
            </div>
          </div>
          <div class="row align-items-center mt-4">
            <div class="col">
              <input type="email" class="form-control" placeholder="Email">
            </div>
          </div>
          <div class="row align-items-center mt-4">
            <div class="col">
              <input type="password" class="form-control" placeholder="Password">
            </div>
            <div class="col">
              <input type="password" class="form-control" placeholder="Confirm Password">
            </div>
          </div>
          <div class="row justify-content-start mt-4">
            <div class="col">
              <div class="form-check">
                <label class="form-check-label">
                  <input type="checkbox" class="form-check-input">
                  I Read and Accept <a href="https://www.froala.com">Terms and Conditions</a>
                </label>
              </div>

              <button class="btn btn-purple mt-4">Submit</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

<!-- Default form login -->
<form class="text-center border border-light p-5" action="#!">

    <p class="h4 mb-4">Sign in</p>

    <!-- Email -->
    <input type="email" id="defaultLoginFormEmail" class="form-control mb-4" placeholder="E-mail">

    <!-- Password -->
    <input type="password" id="defaultLoginFormPassword" class="form-control mb-4" placeholder="Password">

    <div class="d-flex justify-content-around">
        <div>
            <!-- Remember me -->
            <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="defaultLoginFormRemember">
                <label class="custom-control-label" for="defaultLoginFormRemember">Remember me</label>
            </div>
        </div>
        <div>
            <!-- Forgot password -->
            <a href="">Forgot password?</a>
        </div>
    </div>

    <!-- Sign in button -->
    <button class="btn btn-info btn-block my-4" type="submit">Sign in</button>

    <!-- Register -->
    <p>Not a member?
        <a href="">Register</a>
    </p>

    <!-- Social login -->
    <p>or sign in with:</p>

    <a href="#" class="mx-2" role="button"><i class="fab fa-facebook-f light-blue-text"></i></a>
    <a href="#" class="mx-2" role="button"><i class="fab fa-twitter light-blue-text"></i></a>
    <a href="#" class="mx-2" role="button"><i class="fab fa-linkedin-in light-blue-text"></i></a>
    <a href="#" class="mx-2" role="button"><i class="fab fa-github light-blue-text"></i></a>

</form>
<!-- Default form login -->

  <section class="fdb-block py-0">
      <div class="container py-5 my-5" style="background-image: url({% static 'imgs/shapes/4.svg' %});">
        <div class=" row justify-content-end">
          <div class="col-12 col-md-8 col-lg-6 col-xl-5 text-left">
            <div class="fdb-box">
              <div class="row">
                <div class="col">
                  <h1>Log In</h1>
                  <p class="lead">Right at the coast of the Semantics, a large language ocean. A small river named Duden.</p>
                </div>
              </div>
              <div class="row">
                <div class="col mt-4">
                  <input type="text" class="form-control" placeholder="Email">
                </div>
              </div>
              <div class="row mt-4">
                <div class="col">
                  <input type="password" class="form-control" placeholder="Password">
                </div>
              </div>
              <div class="row mt-4">
                <div class="col">
                  <button class="btn btn-secondary" type="button">Submit</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>


{% endblock %}

myfirst/templates/create copy.html
{% extends 'layouts/base_layout.html' %} {% load static %} {% block content %}



<section class="mb-4">
  <div class="container">
    {% if messages %} {% for msg in messages %}
    <div class="alert alert-success">{{ msg }}</div>

    {% endfor %} {% endif %}

    <!-- Default form login -->
    <form class="border border-light p-5" action="/posts/store" method="POST">
      {% csrf_token %}


      {% comment %} {% for field in form %}
      <div class="invalid-feedback" style="display:block">
        {{ field.errors }}

      </div>
      {% endfor %} {% endcomment %}
      <!-- Email -->




      <p class="h5 mb-4">Post details</p>

      <div class="form-group mt-4">
        <label for="id_title">Title</label>
        <input type="text" class="form-control" id="id_title" name="title" value="{{form.title.value}}">
        <div class="invalid-feedback" style="display:block">
          {{ form.title.errors }}
        </div>

      </div>

      <div class="form-group mt-4">
        <label for="id_body">Body</label>
        <input type="text" class="form-control" id="id_body" name="body" value="{{form.body.value}}">
        <div class="invalid-feedback" style="display:block">
          {{ form.body.errors }}
        </div>
      </div>

      {% for field in form %}

      <div class="form-group mt-4">
        <label for="{{field.id_for}}">Title</label>
        <input type="text" class="form-control" id="id_title" name="title" value="{{form.title.value}}">
        <div class="invalid-feedback" style="display:block">
          {{ form.title.errors }}
        </div>

        {% endfor %}
        {% comment %} <input type="text" id="title" name="title" class="form-control mb-4" placeholder="Title"
          value="{{form.title.value}}" /> {% endcomment %}

        <!-- Password -->
        {% comment %} <input type="textarea" id="body" name="body" class="form-control mb-4" placeholder="Body"
          value="{{form.body.value}}" /> {% endcomment %}

        {% comment %} {{form.as_p}} {% endcomment %}

        <!-- Sign in button -->
        <button class="btn btn-purple my-4" type="submit">Post</button>
    </form>
    <!-- Default form login -->
  </div>
</section>

{% endblock %}

myfirst/templates/create.html
{% extends 'layouts/base_layout.html' %}

{% load widget_tweaks %}

{% load static %}

{% block content %}


<section class="mb-4">
  <div class="container">
    {% if messages %}
    {% for msg in messages %}

    <div class="alert alert-{{msg.tags}}">{{ msg }}</div>

    {% endfor %}
    {% endif %}


    {% comment %} {% for field in form %}
    <div class="invalid-feedback" style="display: block">
      {{ field.errors }}
    </div>
    {% endfor %} {% endcomment %}

    <hr>

    <h2>Create New Post</h2>

    <!-- Default form -->
    <form class="border border-light p-5 purple-text" action="{% url 'post_create' %}" method="POST">
      {% csrf_token %}
      <p></p>

      <p></p>
      <!-- way to use django form -->
      <div class="form-group mt-4">
        {{form.title.label_tag }}
        {{ form.title|add_class:"form-control" }}
        <div class="invalid-feedback" style="display:block">
          {{ form.title.errors }}
        </div>
      </div>

      <!-- way to input with html form -->
      <div class="form-group mt-4">
        <label for="id_body">Body</label>
        <input type="text" class="form-control" id="id_body" name="body" value="{{form.body.value|default:''}}">
        <div class="invalid-feedback" style="display:block">
          {{ form.body.errors }}
        </div>
      </div>



      <!-- Sign in button -->
      <button class="btn btn-purple my-4" type="submit">Post</button>
    </form>

  </div>
</section>

{% endblock %}

myfirst/templates/index.html
{% extends 'layouts/base_layout.html' %}
{% load static %}
{% block content %}

<!-- Jumbotron -->
<div class="jumbotron text-center blue-grey lighten-5">
  <!-- Title -->
  <h2 class="card-title h2">All posts list</h2>

  <!-- Subtitle -->
  <p class="indigo-text my-4 font-weight-bold">
    Powerful and free Material Design UI KIT
  </p>

  <hr class="my-4 pb-2" />

  <button class="btn purple-gradient btn-rounded">
    Thank You For Visiting<i class="far fa-gem ml-1"></i>
  </button>
</div>
<!-- Jumbotron -->

<section>
  <div class="container">
    {% if messages %}
    {% for msg in messages %}

    <div class="alert alert-{{msg.tags}}">{{ msg }}</div>

    {% endfor %}
    {% endif %}

    <a class="btn btn-purple" href="{% url 'post_create' %}">Create</a>
    <hr>
    {% for item in posts %}
    <!-- Card -->
    <div class="card mb-4">
      <!-- Card content -->
      <div class="card-body">
        <!-- Title -->
        <h4 class="card-title">{{item.title}}</h4>
        <!-- Text -->
        <p class="card-text">{{item.body}}</p>
        <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
        <a class="btn btn-outline-purple btn-sm" href="{% url 'post_update' post_id=item.id %}">Update</a>
      </div>
      <!-- Card content -->
    </div>
    <!-- Card -->

    {% endfor %}
  </div>
</section>

{% endblock %}

myfirst/templates/show.html
{% extends 'layouts/base_layout.html' %} {% load static %} {% block content %}

<!-- Jumbotron -->
<div class="jumbotron text-center blue-grey lighten-5">
  <!-- Title -->
  <h2 class="card-title h2">Single post Details</h2>

  <!-- Subtitle -->
  <p class="indigo-text my-4 font-weight-bold">
    Powerful and free Material Design UI KIT
  </p>
</div>
<!-- Jumbotron -->

<section>
  <div class="container">
    <!-- Card -->
    <div class="card mb-4">
      <!-- Card content -->
      <div class="card-body">
        <!-- Title -->
        <h4 class="card-title">{{post.title}}</h4>
        <!-- Text -->
        <p class="card-text">{{post.body}}</p>
        <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
        <button type="button" class="btn btn-purple btn-md">Read more</button>
      </div>
      <!-- Card content -->
    </div>
    <!-- Card -->
  </div>
</section>

{% endblock %}

myfirst/templates/update copy.html
{% extends 'layouts/base_layout.html' %} {% load static %} {% block content %}

<!-- Jumbotron -->
<div class="jumbotron text-center blue-grey lighten-5">
  <!-- Title -->
  <h2 class="card-title h2">Create a new post</h2>

  <!-- Subtitle -->
  <p class="indigo-text my-4 font-weight-bold">
    Powerful and free Material Design UI KIT
  </p>
</div>
<!-- Jumbotron -->

<section class="mb-4">
  <div class="container">
    {% if messages %} {% for msg in messages %}
    <div class="alert alert-success">{{ msg }}</div>

    {% endfor %} {% endif %}

    <!-- Default form login -->
    <form class="border border-light p-5" action="" method="POST">
      {% csrf_token %}

      <p class="h5 mb-4">Post details</p>

      <div class="form-group mt-4">
        <label for="id_title">Title</label>
        <input type="text" class="form-control" id="id_title" name="title" value="{{form.title.value}}" />
        <div class="invalid-feedback" style="display: block">
          {{ form.title.errors }}
        </div>
      </div>

      <div class="form-group mt-4">
        <label for="id_body">Body</label>
        <input type="text" class="form-control" id="id_body" name="body" value="{{form.body.value}}" />
        <div class="invalid-feedback" style="display: block">
          {{ form.body.errors }}
        </div>
      </div>

      <!-- Sign in button -->
      <button class="btn btn-purple my-4" type="submit">Post</button>
    </form>
    <!-- Default form login -->
  </div>
</section>

{% endblock %}

myfirst/templates/update.html
{% extends 'layouts/base_layout.html' %}
{% load widget_tweaks %}
{% load static %}



{% block content %}

<hr>

<section class="mb-4">
  <div class="container">
    {% if messages %}
    {% for msg in messages %}
    <div class="alert alert-success">{{ msg }}</div>

    {% endfor %}
    {% endif %}


    <!-- Default form login -->
    <form class="border border-light p-5" action="" method="POST">
      {% csrf_token %}

      <p class="h5 mb-4">Post details</p>


      <div class="form-group mt-4">
        {{form.title.label_tag }}
        {{ form.title|add_class:"form-control" }}
        <div class="invalid-feedback" style="display:block">
          {{ form.title.errors }}
        </div>
      </div>

      <div class="form-group mt-4">
        <label for="id_body">Body</label>
        <input type="text" class="form-control" id="id_body" name="body" value="{{form.body.value}}" />
        <div class="invalid-feedback" style="display: block">
          {{ form.body.errors }}
        </div>
      </div>

      <!-- Sign in button -->
      <button class="btn btn-purple my-4" type="submit">UPDATE</button>
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-red" data-toggle="modal" data-target="#basicExampleModal">
        DELETE
      </button>

    </form>




    <!-- Modal -->
    <div class="modal fade" id="basicExampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
      aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">

          <div class="modal-body">
            <h3>ARE YOU SURE ???</h3>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <a class="btn btn-red" href="{% url 'post_delete' post_id=pk_id %}">Delete</a>


          </div>
        </div>
      </div>
    </div>
    <!-- Default form login -->
  </div>
</section>

{% endblock %}